apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-state-store
spec:
  type: state.sqlserver
  version: v1
  metadata:
  - name: connectionString    
    secretKeyRef:
      name: mssql
      key:  SqlDB-state

auth:
  secretStore: local-secret-store